name: log_4_dart_2
description: A dart package for logging, with multiple and configurable appenders.
version: 0.3.3
homepage: https://github.com/Ephenodrom/Dart-Log-4-Dart-2
author: Daniel Linsenmeier <daniel@ephenodrom.de>

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  basic_utils: ^2.4.7
  intl: ^0.16.0
  mailer: ^3.0.4
  mysql1: ^0.17.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
