name: log_4_dart_2
description: A dart package for logging, with multiple and configurable appenders.
version: 1.0.0 # Changed Logger.init, thus breaking changes
homepage: https://github.com/Ephenodrom/Dart-Log-4-Dart-2
#author: Daniel Linsenmeier <daniel@ephenodrom.de> # https://stackoverflow.com/a/59942840/132396

environment:
  sdk: '>=2.16.0-0 <3.0.0'

dependencies:
  analyzer: ^4.0.0
  basic_utils: ^4.2.1
  intl: ^0.17.0
  mailer: ^5.1.0
  meta: ^1.7.0
  mysql1: ^0.19.2

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.6.0
