name: log_4_dart_2
description: A dart package for logging, with multiple and configurable appenders.
version: 0.4.0
homepage: https://github.com/Ephenodrom/Dart-Log-4-Dart-2
author: Daniel Linsenmeier <daniel@ephenodrom.de>

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  analyzer: ^4.0.0
  basic_utils: ^4.2.1
  intl: ^0.17.0
  mailer: ^5.1.0
  meta: ^1.7.0
  mysql1: ^0.19.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
